version: '3'
services:
  local:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    image: server-api
    volumes:
      - ./server:/usr/src/app/server
    container_name: server_container_local
    ports:
      - '3000:3000'
      - '9229:9229'
    tty: true
    command: npm run dev
  server:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.server
    container_name: server_container
    ports:
      - 3000:3000
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.front
    container_name: app_container
    ports:
      - 4200:4200
    links:
      - server
    volumes:
       - ./app:/usr/src/app/app-ui
    command: npm start
networks:
  default:
    name: you2musik