export interface Video {
    kind: String,
    etag: String,
    id: {
        kind: String,
        videoId: String
    },

    isDownloading: boolean,
    downloadingProgress: number,
    snippet: {
        channelTitle: String,
        liveBroadcastContent: String,
        publishTime: String,

        publishedAt: String,
        channelId: String,
        title: String,
        description: String,
        thumbnails: {
            default: {
                url: String,
                width: number,
                height: number
            },
            medium: {
                url: String,
                width: number,
                height: number
            },
            hight: {
                url: String,
                width: number,
                height: number
            }
        }
    },
    contentDetails: {
        duration: String,
        dimension: String,
        definition: String,
        caption: String,
        licensedContent: boolean,
        contentRating: Object,
        projection: String
    },
    status: {
        uploadStatus: String,
        privacyStatus: String,
        license: String,
        embeddable: boolean,
        publicStatsViewable: boolean,
        madeForKids: boolean
    },
    statistics: {
        viewCount: String,
        likeCount: String,
        favoriteCount: String,
        commentCount: String
    }

}

export interface VideosResponse {
    kind: String,
    etag: String,
    nextPageToken: String,
    regionCode: String,
    pageInfo: {
        totalResults: BigInteger,
        resultsPerPage: number
    },
    items: Array<Video>

}

/*
contentDetails: {duration: '04:04', dimension: '2d', definition: 'hd', caption: 'false', licensedContent: true, …}
etag: "zqIZ2sn3LEVCdnKPk_DWQlIr7oE"
id: "QDYfEBY9NM4"
kind: "youtube#video"
snippet: {publishedAt: '2018-06-17T11:16:32Z', channelId: 'UC2XdaAVUannpujzv32jcouQ', title: 'Let It Be (Remastered 2009)', description: 'Provided to YouTube by Universal Music Group\n\nLet …icist: Paul McCartney\n\nAuto-generated by YouTube.', thumbnails: {…}, …}
statistics: {viewCount: '106041601', likeCount: '885061', favoriteCount: '0', commentCount: '15244'}
status: {uploadStatus: 'processed', privacyStatus: 'public', license: 'youtube', embeddable: true, publicStatsViewable: true, …}
*/